**420-A58-SF - Algorithmes d'apprentissage non supervisé - Hiver 2026 - Spécialisation technique en Intelligence Artificielle**<br/>
MIT License - Copyright (c) 2026 Mikaël Swawola

# Évaluation formative #3

| | |
|---|---|
| **Durée** | 30 minutes |
| **Travail** | Individuel |
| **Documents** | Autorisés |
| **Remise** | Remettre ce notebook complété sur Lea |

## Barème

| Question | Points |
|----------|--------|
| Q1.1 | 2 |
| Q1.2 | 2 |
| Q1.3 | 2 |
| Q1.4 | 2 |
| Q1.5 | 2 |
| **Total** | **10** |

---
# Fouille de données basée sur les règles d'association (10 points)

Passionné de cinéma, vous souhaitez tenter de découvrir quels acteurs et quelles actrices apparaissent souvent dans un même film d'action. Votre choix se porte sur la technique des règles d'association.
**Chargez le jeu de données `action-movies.csv` et répondez aux question suivantes.**

### Question 1-1 - Après avoir bien observé le jeu de données `action-movies.csv`, quels éléments représentent les "items" et quels éléments représentent les "baskets" du modèle 'market-basket' ? (2 points)

### ----- Votre réponse ci-dessous -----

In [4]:
# Réponse rédactionnelle
# Les "items" représentent les acteurs et actrices présents dans les films d'action.
# Les "baskets" représentent les films eux-mêmes, chaque film contenant un ensemble d'acteurs et d'actrices.

### Question 1-2 - Quel est le support de la paire { Jet Li, Sylvester Stallone } ? (2 points)

### ----- Votre réponse ci-dessous -----

In [32]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

data = pd.read_csv('../../data/action-movies.csv')
transactions = list(data["cast"].apply(lambda x:x.split(',')))

te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_data,columns=te.columns_)

freq = apriori(df, min_support=0.1, use_colnames=True)
freq

     support                                           itemsets
0   0.173913                 frozenset({Arnold Schwarzenegger})
1   0.173913                         frozenset({Carl Weathers})
2   0.391304                        frozenset({Dolph Lundgren})
3   0.217391                         frozenset({Jason Statham})
4   0.217391                 frozenset({Jean-Claude Van Damme})
..       ...                                                ...
64  0.130435  frozenset({Jet Li, Dolph Lundgren, Jason Stath...
65  0.130435  frozenset({Dolph Lundgren, Jason Statham, Sylv...
66  0.130435  frozenset({Jet Li, Dolph Lundgren, Sylvester S...
67  0.130435  frozenset({Jet Li, Jason Statham, Sylvester St...
68  0.130435  frozenset({Jet Li, Dolph Lundgren, Jason Stath...

[69 rows x 2 columns]

In [30]:
freq[freq["itemsets"].apply(lambda s: "Sylvester Stallone" in s and "Jet Li" in s)]

     support                                           itemsets
22  0.130435            frozenset({Jet Li, Sylvester Stallone})
32  0.130435  frozenset({Jet Li, Dolph Lundgren, Sylvester S...
38  0.130435  frozenset({Jet Li, Jason Statham, Sylvester St...
43  0.130435  frozenset({Jet Li, Randy Couture, Sylvester St...
45  0.130435  frozenset({Jet Li, Terry Crews, Sylvester Stal...
48  0.130435  frozenset({Jet Li, Dolph Lundgren, Jason Stath...
53  0.130435  frozenset({Jet Li, Randy Couture, Dolph Lundgr...
55  0.130435  frozenset({Jet Li, Terry Crews, Dolph Lundgren...
57  0.130435  frozenset({Jet Li, Randy Couture, Jason Statha...
59  0.130435  frozenset({Jet Li, Terry Crews, Jason Statham,...
61  0.130435  frozenset({Jet Li, Randy Couture, Terry Crews,...
62  0.130435  frozenset({Jet Li, Dolph Lundgren, Jason Stath...
64  0.130435  frozenset({Jet Li, Dolph Lundgren, Jason Stath...
66  0.130435  frozenset({Jet Li, Dolph Lundgren, Sylvester S...
67  0.130435  frozenset({Jet Li, Jason Statham, Sylvester St...
68  0.130435  frozenset({Jet Li, Dolph Lundgren, Jason Stath...

 ### Question 1-3 - Considérant un seuil de support de 0.10, combien d'itemsets sont fréquents ? (2 points)

### ----- Votre réponse ci-dessous -----

In [33]:
len(freq)

69

### Question 1-4 - Toujours en considérant un seuil de support de 0.10, quel est l'indice de confiance de la règle d'association { Jet Li } => { Sylvester Stallone } ? (2 points)

### ----- Votre réponse ci-dessous -----

In [35]:
# Calcul de l'indice de confiance pour la règle { Jet Li } => { Sylvester Stallone }
from mlxtend.frequent_patterns import association_rules

rules = association_rules(freq, metric="confidence", min_threshold=0.10)
rule = rules[(rules['antecedents'] == frozenset({'Jet Li'})) & (rules['consequents'] == frozenset({'Sylvester Stallone'}))]

# Réponse rédactionnelle
rule['confidence'].values[0] if not rule.empty else "Règle non trouvée"

np.float64(0.42857142857142855)

### Question 1-5 - La règle { Jet Li } => { Sylvester Stallone } est-elle intéressante ? Justifiez votre réponse. (2 points)

### ----- Votre réponse ci-dessous -----

In [43]:
nb_films_avec_stallone = freq[freq["itemsets"] == frozenset({"Sylvester Stallone"})]
print(nb_films_avec_stallone)
freq_stallone = len(nb_films_avec_stallone) / len(df)
print(freq_stallone)
Interet = 0.42857142857142855 - freq_stallone
print(Interet)

    support                         itemsets
7  0.391304  frozenset({Sylvester Stallone})
0.043478260869565216
0.3850931677018633

---
## Fin de l'évaluation formative #3